# Generated by Django 4.2.1 on 2023-05-25 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='favorite_movies',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.AddField(
            model_name='userranking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.movie'),
        ),
        migrations.AddField(
            model_name='userranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userranking',
            unique_together={('user', 'position')},
        ),
    ]
