# Generated by Django 4.2.1 on 2023-05-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_rankedmovie_options_alter_rankedmovie_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankedmovie',
            unique_together={('ranking', 'position')},
        ),
    ]
