# Generated by Django 4.2.1 on 2023-05-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_rename_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='mainpage_movie',
        ),
        migrations.AlterModelTable(
            name='rankedmovie',
            table='mainpage_rankedmovie',
        ),
        migrations.AlterModelTable(
            name='userranking',
            table='mainpage_userranking',
        ),
    ]
