# Generated by Django 4.2.1 on 2023-05-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_remove_rankedmovie_movie_remove_userranking_movies_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankedmovie',
            unique_together=set(),
        ),
    ]
